name= input('What is your name?')
age= input('What is your age?')
country = input('Where are you from?')
location= input('Where are you from?')
print('Hello {}, you are {} years of age and you come from {}.'.format(name, age, location))